[build-system]
build-baclemd = "setuptools.build_meta"
requires = [
    "setuptools",
]

[project]
authors = [
    { name = "Habarug" },
]
dependencies = [
    "matplotlib",
    "numpy",
    "pandas",
    "thefuzz",
    "wikitextparser",
]
description = "Python package to plot StarVaders stats"
name = "StarVadersStats"
readme = "README.md"
version = "0.1"

[project.optional-dependencies]
dev = [
    "pre-commit",
    "ruff",
]

[tool.ruff]
exclude = [
    "*__init__.py",
]

[tool.ruff.lint]
extend-select = [
    "I",
]
